kind: pipeline
name: default

steps:
- name: builder
  image: ubuntu:19.04
  environment:
    VERSION: 18.06
  commands:
  - apt update
  - apt install -y git build-essential libncurses5-dev python unzip
  - mkdir -p /data/lede
  - cd /data/lede
  - git clone https://github.com/openwrt/openwrt.git
  - cd openwrt/
  - git checkout openwrt-$VERSION
  - ./scripts/feeds update -a
  - ./scripts/feeds install -a
  - make defconfig
  - make download
  - make -j $(getconf _NPROCESSORS_ONLN)  V=s
  volumes:
  - name: cache
    path: /cache
