kind: pipeline
name: default

steps:
- name: builder
  image: ubuntu:19.04
  environment:
    VERSION: 18.06
    FORCE_UNSAFE_CONFIGURE: 1
    MINIO_TOKEN:
      from_secret: MINIO_TOKEN
  commands:
  - apt -qq update
  - apt -qq install -y git build-essential libncurses5-dev python unzip gawk wget
  - wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/bin/mc && chmod +x /usr/bin/mc
  - /usr/bin/mc config host add myminio https://minio.lukasmrtvy.cz admin $MINIO_TOKEN
  - mkdir -p /cache/build/
  - cd /cache/build/
  - git clone https://github.com/openwrt/openwrt.git
  - cd openwrt/
  - git checkout openwrt-$VERSION
  - mv $DRONE_WORKSPACE/.config ./
  #- mv $DRONE_WORKSPACE/.kconfig ./
  #- mv $DRONE_WORKSPACE/.kconfig.sh ./ && chmod +x kconfig.sh && ./kconfig.sh
  - ./scripts/feeds update -a
  - ./scripts/feeds install -a
  - make defconfig
  #- make download -j $(getconf _NPROCESSORS_ONLN)
  ###- make -j $(getconf _NPROCESSORS_ONLN)  V=s | tee make.output
  #- make -j$((`nproc`+1)) | tee -a make.output
  #- make -j1 V=s | tee -a /cache/make.output
  - make -j1 V=s | /usr/bin/mc pipe myminio/drone/aha.output
  volumes:
  - name: cache
    path: /cache
 
- name: test
  image: alpine:3.9
  commands:
  - ls -lha /cache/ || true
  - ls -lha /cache/build/ || true 
  - ls -lha /cache/build/openwrt/ || true
  - ls -lha /cache/build/openwrt/bin/packages/ || true
  - ls -lha /cache/build/openwrt/bin/ || true
  - ls -lha /cache/build/openwrt/bin/x86/ || true
  - ls -lha /cache/build/openwrt/bin/x86/64 || true
  - ls -lha /cache/build/openwrt/bin/packages/ || true
  - ls -lha /cache/build/openwrt/bin/targets/ || true
  - ls -lha /cache/build/openwrt/bin/targets/x86/ || true
  - ls -lha /cache/build/openwrt/bin/targets/x86/64/ || true
  volumes:
  - name: cache
    path: /cache
  when:
    status:
    - success
    - failure

- name: upload
  image: plugins/s3
  settings:
    bucket: drone
    source: /cache/make.output
    target: make.${DRONE_BUILD_NUMBER}.output
    path_style: true
    endpoint: http://minio:9000
    access_key: admin
    secret_key:
      from_secret: MINIO_TOKEN
  volumes:
  - name: cache
    path: /cache
  when:
    status:
    - success
    - failure


volumes:
- name: cache
  temp: {}
