kind: pipeline
name: default

steps:
- name: builder
  image: ubuntu:19.04
  environment:
    VERSION: 18.06
    FORCE_UNSAFE_CONFIGURE: 1
  commands:
  - apt -qq update
  - apt -qq install -y git build-essential libncurses5-dev python unzip gawk wget
  - mkdir -p /cache/data/lede
  - cd /cache/data/lede
  - git clone https://github.com/openwrt/openwrt.git
  - cd openwrt/
  - git checkout openwrt-$VERSION
  - ./scripts/feeds update -a
  - ./scripts/feeds install -a
  - make defconfig
  - make download -j $(getconf _NPROCESSORS_ONLN)
  - make -j $(getconf _NPROCESSORS_ONLN)  V=s | tee make.output
  #- make -j1 V=s
  volumes:
  - name: cache
    path: /cache
 
- name: test
  image: alpine:3.9
  commands:
  - ls -lha /cache/data/lede/bin/x86/64
  volumes:
  - name: cache
    path: /cache

- name: upload
  image: plugins/s3
  settings:
    bucket: drone-logs
    source: make.output
    target: make.${DRONE_BUILD_NUMBER}.output
    path_style: true
    endpoint: http://minio:9000

volumes:
- name: cache
  temp: {}
